ti-am62: ti-edgeai-firmware.bbappend: Fix deployment ordering for ti-dm-fw
Issue: LIN1024-8722

The previous commit 5918b11f7eb0f (ti-am62: Add dependency on ti-dm-fw in ti-edgeai-firmware.bbappend)
tried to solve the following problem:

ERROR: ti-dm-fw-11.00.06-r4.0 do_deploy: Recipe ti-dm-fw is trying to install files
into a shared area when those files already exist. The files and the manifests listing them are:
deploy/images/ti-am62/ti-dm/am62axx/ipc_echo_testb_mcu1_0_release_strip.xer5f.signed
(matched in manifest-ti_am62-ti-edgeai-firmware.deploy)

But sometimes, it cannot guarantee that do_deploy of ti-edgeai-firmware is executed after
do_deploy of ti-dm-fw. Ensure that the do_deploy task for ti-edgeai-firmware
runs only after the ti-dm-fw recipe's do_deploy task has completed. This fixes
issues where deployment artifacts may be missing or out-of-date due to improper
task ordering.

- Remove global DEPENDS on ti-dm-fw, as it is not sufficient for do_deploy ordering
- Add explicit do_deploy[depends] for ti-dm-fw:do_deploy

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>