ti-am62: Add dependency on ti-dm-fw in ti-edgeai-firmware.bbappend
Issue: LIN1024-8436

This commit adds `DEPENDS += "ti-dm-fw"` to the ti-edgeai-firmware.bbappend file.
The change ensures that ti-dm-fw is built before ti-edgeai-firmware, resolving
deployment conflicts caused by overlapping files in the shared area.

To fix below building issue:
ERROR: ti-dm-fw-11.00.06-r4.0 do_deploy: Recipe ti-dm-fw is trying to install files
into a shared area when those files already exist. The files and the manifests listing them are:
 deploy/images/ti-am62/ti-dm/am62axx/ipc_echo_testb_mcu1_0_release_strip.xer5f.signed
    (matched in manifest-ti_am62-ti-edgeai-firmware.deploy)
 deploy/images/ti-am62/ti-dm/am62axx/ipc_echo_testb_mcu1_0_release_strip.xer5f
    (matched in manifest-ti_am62-ti-edgeai-firmware.deploy)
Please adjust the recipes so only one recipe provides a given file.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>